### ISSUE TITLE
Different Path for Download Vs Complete

### ISSUE THREAD

**Issue by alex285** [haecker-felix/Fragments#12]
hello! i would like to have an option that i could set:

**Downloading**
```
$HOME/Downloads/Torrents
```
**Completed**
```
$HOME/Downloads/Torrents/Complete
```

**Comment by bertob** [comment]
@alex285 What use cases are you trying to address with that?
Could you describe some real-world scenarios?

**Comment by alex285** [comment]
hello @bertob, this is a very typical functionality on torrent clients for the following reason

Imagine you have 50 torrents downloading. 30 of them are complete. What i want to do is to remove them from seeding (from Fragments apps), and then move them to an external disk drive. If all torrents are on the same location, it would be impossible to tell what is finished what is not, so i can cut/paste it

**Comment by bertob** [comment]
> Imagine you have 50 torrents downloading. 30 of them are complete

Definitely sounds like an edge case, very few people download that many things at once. I suspect that this is a non-issue for the people this app is targeted towards (casual torrenters who download a few files per week at best).

That said, I'm open to addressing this if we can do it without adding a preference. Perhaps we could keep the files in a a temporary directory while downloading, and only move them to the Downloads folder when complete?

**Comment by alex285** [comment]
> Definitely sounds like an edge case, very few people download that many things at once. 

not really! 50 downloads for someone who torrents series is really nothing. even if you're downloading 25 episodes (which is roughly 2 seasons), you still can have 100-150 on seeding, so mixing complete and incomplete files in the same directory might not work for everyone

>  this is a non-issue for the people this app is targeted towards

i understand the point of Fragments isn't to be a QBittorrent, but you might want to check on [Torrex Torrent Client ](https://www.microsoft.com/en-us/store/p/torrex-lite-torrent-downloader/9wzdncrfjb3d)that pretty much has the same purpose as Fragments, and it is available on Phones and Game Consoles too

anyway, feel free to close the bug report!

**Comment by haecker-felix** [comment]
It isn't a problem to use a another folder for downloading torrents. I think it makes sense, because you only want to see completed torrents in your selected download folder.

It shouldn't be necessary to make the "downloading"-folder configurable, because no one needs half downloaded files.

**Comment by alex285** [comment]
@haecker-felix 
>... because no one needs half downloaded files.

that is not quite true either, because you need half downloading files, in case you want to watch as you stream, which means there should be an option for sequential download too

this is a very common case to torrent users. You're downloading a torrent that has 12 episodes. You should be able see all torrent contained-files on Fragments (thats another bug currently) and prioritize episode 01 that you want to instantly watch

on the app you may have a play button, that opens the default video player, but you might want to watch on a different player than default (very common case), so you will need to open downloading directory. Sure downloading directory might be pre-configured by the app, but you just decrease usability, without any benefits, plus sometimes you may want to add a half-download file, to complete it

i dont want to sound like im trying to force something, im just saying that there is some standard functionality in all torrent clients, that i dont think it is a good idea to skip it, otherwise you end up to build a worse Transmission ..that perhaps just looks better :)
