### ISSUE TITLE
Bug: space before queue after DnD

### ISSUE THREAD

**Issue by bertob** [haecker-felix/Fragments#17]
How to reproduce:
1. start 5 torrents, such that there are 2 active ones in the queue
2. DnD the second one to the position of the first one
3. Pause all 5 torrents

![fragments-dnd-space](https://user-images.githubusercontent.com/1908896/38192032-5661308c-366b-11e8-9b73-1ea4848020e8.png)

**Comment by haecker-felix** [comment]
Fixed.
