### ISSUE TITLE
fragments is not dowloading anything

### ISSUE THREAD

**Issue by legacychimera247** [haecker-felix/Fragments#23]
hi there,
i tried fragments with 4 different magnet links and in 10 minutes none even started downloading informations, tried them in transmission and in 1 minute all of them where downloading (and transmission is slower if compared to deluge). any reason for that?maybe i should have waited more?

**Comment by haecker-felix** [comment]
Any special network configurations? Proxy server? Are you on a company network?

Please enable the debug logging. Edit this file:

_/home/username/.var/app/de.haeckerfelix.Fragments/config/fragments/settings.json_

And change "message-level" to "3".
Now start Fragments in a terminal with:

`flatpak run de.haeckerfelix.Fragments`

You should see a lot of messages / debug information. Now add a torrent. Please copy the complete output of Fragments, and paste it here.

**Comment by legacychimera247** [comment]
the other day i had the upgrade to fedora 28...this seems to have solved my problem as fragments is pefectly working now...will close that and reopen if needed...
