### ISSUE TITLE
Option to add magnet link

### ISSUE THREAD

**Issue by m110s** [haecker-felix/Fragments#6]
So far we can open magnet links only if Fragments is set for default torrent/magnet app.
Because it's still in early development I prefer Transmission for default app, therefore it's impossible to open magnet links. 
Please, add option to open (paste) magnet so we can easily test app, because most torrents are now downloadable via magnets.

**Comment by bertob** [comment]
@haecker-felix could we automatically read the content of the clipboard when the app comes into focus, and if it contains a magnet link we display a little banner to add the torrent? That would be a more streamlined workflow than adding a button with a popover etc.

**Comment by bertob** [comment]
Here's a mockup of what that could look like:

![fragments-addmagnet](https://user-images.githubusercontent.com/1908896/37392253-ea7bdd2e-276d-11e8-9d9a-fedb1fa80534.png)

**Comment by m110s** [comment]
Looks good to me.

**Comment by haecker-felix** [comment]
![fragments_magnet_demo](https://user-images.githubusercontent.com/6001248/37537598-604fa314-294e-11e8-8742-7f3af7f2ade7.gif)
